# Generated by Django 3.1.7 on 2021-04-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=1, verbose_name='توضیحات و بیوگرافی شما'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(default=1, verbose_name='تلفن'),
            preserve_default=False,
        ),
    ]
