# Generated by Django 3.1.7 on 2021-03-20 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='jobs.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام استان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس استان')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='jobs.cities', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=300, verbose_name='نام شرکت')),
                ('description', models.TextField(verbose_name='توضیحات شغلی')),
                ('employer_description', models.TextField(verbose_name='نفش کارمند در شرکت')),
                ('address', models.TextField(verbose_name='آدرس شرکت شما')),
                ('price', models.CharField(choices=[('توافقی', 'توافقی'), ('2 تا 3 میلیون', '2 تا 3 میلیون'), ('8 تا 9 میلیون', '8 تا 9 میلیون'), ('10 تا 12 میلیون', '10 تا 12 میلیون'), ('12 تا 20 میلیون', '12 تا 20 میلیون'), ('دیگر قیمت ها', 'دیگر قیمت ها')], default='i', max_length=200, verbose_name='حقوق')),
                ('Type', models.CharField(choices=[('دور کاری', 'دور کاری'), ('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('کارآموزی', 'کارآموزی'), ('پروژه ای', 'پروژه ای')], default='d', max_length=200, verbose_name='وضعیت شغلی')),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'منقضی شده')], default='i', max_length=200, verbose_name='وضعیت')),
                ('soldiering', models.CharField(choices=[('معاف', 'معاف'), ('پایان خدمت', 'پایان خدمت'), ('مهم نیست', 'مهم نیست')], default='مهم نیست', max_length=200, verbose_name='وضعیت نظام وظیفه')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('مهم نیست', 'مهم نیست')], default='مهم نیست', max_length=200, verbose_name='جنسیت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.category', verbose_name='دسته بندی')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.cities', verbose_name='شهر')),
                ('important', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='مهارت های لازم')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_services_items', to='taggit.tag')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.jobs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='service',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='services', through='jobs.Services', to='taggit.Tag', verbose_name='مهارت های لازم'),
        ),
    ]
