# Generated by Django 3.1.7 on 2021-03-19 14:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=300, verbose_name='عنوان شغلی')),
                ('description', models.TextField(verbose_name='توضیحات شغلی')),
                ('address', models.TextField(verbose_name='آدرس شرکت شما')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
