# Generated by Django 3.1.7 on 2021-03-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210319_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.CharField(max_length=300, verbose_name='نام شرکت'),
        ),
    ]
