# Generated by Django 3.1.7 on 2021-03-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210319_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حقوق'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='services',
            field=models.ManyToManyField(to='jobs.Services', verbose_name='مهارت های مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='soldiering',
            field=models.CharField(choices=[('d', 'پایان خدمت'), ('p', 'معاف'), ('i', 'مهم نیست')], default='i', max_length=1, verbose_name='وضعیت نظام وظیفه'),
        ),
    ]
