# Generated by Django 3.1.4 on 2021-03-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='phone',
            field=models.CharField(default=1, max_length=300, verbose_name='تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massage',
            name='revicer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='دریافت کننده'),
            preserve_default=False,
        ),
    ]
