# Generated by Django 3.1.7 on 2021-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210320_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Type',
            field=models.CharField(choices=[('دور کاری', 'دور کاری'), ('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('کارآموزی', 'کارآموزی'), ('پروژه ای', 'پروژه ای')], default='d', max_length=200, verbose_name='وضعیت شغلی'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='price',
            field=models.CharField(choices=[('توافقی', 'توافقی'), ('2 تا 3 میلیون', '2 تا 3 میلیون'), ('8 تا 9 میلیون', '8 تا 9 میلیون'), ('10 تا 12 میلیون', '10 تا 12 میلیون'), ('12 تا 20 میلیون', '12 تا 20 میلیون'), ('دیگر قیمت ها', 'دیگر قیمت ها')], default='i', max_length=200, verbose_name='حقوق'),
        ),
    ]
