# Generated by Django 3.1.7 on 2021-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210404_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdf', verbose_name='فایل رزومه'),
            preserve_default=False,
        ),
    ]
