# Generated by Django 3.1.7 on 2021-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210405_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_expire',
            field=models.BooleanField(default=False, verbose_name='ایا منقضی شده است؟'),
        ),
    ]
