# Generated by Django 3.1.7 on 2021-04-15 07:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobs_is_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='is_expire',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات شغلی'),
        ),
    ]
