# Generated by Django 3.1.7 on 2021-04-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.PositiveIntegerField(verbose_name='تلفن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر شما')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('bio', models.TextField(verbose_name='توضیحات و بیوگرافی شما')),
                ('github', models.URLField(blank=True, null=True, verbose_name='لینک گیتهاب')),
                ('linkendin', models.URLField(blank=True, null=True, verbose_name='لینکندین')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت شما')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('whatsApp', models.PositiveIntegerField(blank=True, max_length=50, null=True, verbose_name='واتساپ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, verbose_name='مهارت')),
                ('college', models.CharField(max_length=300, verbose_name='دانشکده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=50, null=True, verbose_name='مهارت')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='چند درصد در این مهارت حرفه ای هستید؟')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پروژه')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='زمینه کاری پروژه')),
                ('link', models.CharField(blank=True, max_length=2084, null=True, verbose_name='لینک پروژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='عکس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام شرکت یا سازمان')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقام شما در شرکت')),
                ('joining_date', models.DateField(verbose_name='تاریخ عضویت')),
                ('ending_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان کاری')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='توضیحات کاری')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
