# Generated by Django 3.1.7 on 2021-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='whatsApp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='واتساپ'),
        ),
    ]
