# Generated by Django 3.1.7 on 2021-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210426_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
