# Generated by Django 3.1.7 on 2021-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_study_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='چند درصد در این مهارت حرفه ای هستید؟'),
        ),
    ]
