# Generated by Django 3.1.7 on 2021-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, verbose_name='نقش شما در پروژه'),
            preserve_default=False,
        ),
    ]
