# Generated by Django 3.1.7 on 2021-04-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
